[platformio]
default_envs = heltec_wifi_lora_32

[env:heltec_wifi_lora_32]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

lib_deps =
  sandeepmistry/LoRa@^0.8.0

build_flags =
  -D TANK_NODE
