[platformio]
default_envs = heltec_wifi_lora_32

[env:heltec_wifi_lora_32]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

lib_deps =
  sandeepmistry/LoRa@^0.8.0
  esp32async/ESPAsyncWebServer@^3.0.6
  esp32async/AsyncTCP@^3.4.10

build_flags =
  -D GATEWAY
