[platformio]
default_envs = heltec_wifi_lora_32

[env:heltec_wifi_lora_32]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  jgromes/RadioLib@^6.4.6
  esp32async/ESPAsyncWebServer@^3.0.6
  esp32async/AsyncTCP@^3.4.10
  olikraus/U8g2@^2.35.30

build_flags =
  -D GATEWAY
  -D LORA_SCK=9
  -D LORA_MISO=11
  -D LORA_MOSI=10
  -D LORA_SS=8
  -D LORA_FREQ_HZ=915E6
